# Generated by Django 5.0 on 2026-06-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactionitem',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
