# Generated by Django 5.0 on 2026-06-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
