# Generated by Django 5.0 on 2026-06-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_item_item_id_item_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='qty',
        ),
    ]
